### ISSUE TITLE
android-x86-8.1-r2 kernel-5.3_si_next rtl8723bu compilation errors

### ISSUE THREAD

**Issue by emelcher** [maurossi/linux#13]
Executing the following commands:
mkdir android-x86
cd android-x86
repo init -u git://git.osdn.net/gitroot/android-x86/manifest -b oreo-x86 -m android-x86-8.1-r2.xml
repo sync --no-tags --no-clone-bundle 
cd  kernel
git remote add maurossi https://github.com/maurossi/linux
git fetch maurossi kernel-5.3_si_next
git checkout FETCH_HEAD
m -j3 iso_img

leads to following output:
/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_get_systime_us':
/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c:359:2: error: implicit declaration of function 'get_monotonic_boottime' [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors

make[2]: *** [/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/rtw_android.c: In function 'rtw_android_priv_cmd':
/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/rtw_android.c:621:62: error: macro "access_ok" passed 3 arguments, but takes just 2
/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/rtw_android.c:621:7: error: 'access_ok' undeclared (first use in this function)
/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/rtw_android.c:621:7: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/rtw_android.o] Error 1
make[1]: *** [_module_/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu] Error 2
make[1]: Leaving directory `/homelocal/elmar/android-x86/out/target/product/x86_64/obj/kernel'
make: *** [sub-make] Error 2
make: Leaving directory `/homelocal/elmar/android-x86/kernel'
[ 10% 11049/102840] target  C: i965_dri_32 <= out/target/prod..._x86/SHARED_LIBRARIES/i965_dri_intermediates/brw_oa_metrics.
ninja: build stopped: subcommand failed.
19:16:02 ninja failed with: exit status 1

#### failed to build some targets (40:57 (mm:ss)) ####

My target has RTL8723BS, do I need rtl8723bu driver ?
If not, how can I disable compilation of rtl8723bu driver ?

**Comment by maurossi** [comment]
Hi,
this error is not due to kernel branch, it is due to external/kernel-drivers project,
where you need to checkout kernel-5.1 branch to be able to build with kernel 5.1 and later

https://github.com/maurossi/kernel-drivers/commits/kernel-5.1

Mauro

**Comment by maurossi** [comment]
That will suffice because rtl8723bs now is already in kernel
Mauro

**Comment by emelcher** [comment]
Resolved the issue doing:
`rm -rf external/cd kernel-drivers/rtl* external/cd kernel-drivers/wl`

complete and corrected command sequence would be:
`mkdir android-x86`
`cd android-x86`
`repo init -u git://git.osdn.net/gitroot/android-x86/manifest -b oreo-x86 -m android-x86-8.1-r2.xml`
`repo sync --no-tags --no-clone-bundle`
`rm -rf external/cd kernel-drivers/rtl* external/cd kernel-drivers/wl`
`cd kernel`
`git remote add maurossi https://github.com/maurossi/linux`
`git fetch maurossi kernel-5.3_si_next`
`git checkout FETCH_HEAD`
`cd ..`
`. build/envsetup.sh`
`lunch android_x86_64-userdebug`
`m -j3 iso_img`

**Comment by maurossi** [comment]
That also work because you removed the target that required updates to build with kernel 5.1 and later,
so removing the target that was not building will of course avoid the build error
Mauro
